### ISSUE TITLE
Add Yup support

### ISSUE THREAD

**Issue by kirillta** [punk-link/management-app#2]
Add [Yup](https://github.com/jquense/yup) to provide consist validation over the project.

1. Set up the project locally
2. Create new git branch `feature/MA-2-yup_support`
3. Install Yup
4. Add Yup to the field validation at `Login` and `SignUp` pages. See [Formik](https://formik.org/docs/overview) docs, esp. [that](https://formik.org/docs/api/errormessage) example.

Bonus task:
1. Use `ValidationSchema` in your solution

**Comment by KiPavlov** [comment]
Hey, i've finished;)
